services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xakker_app
    restart: unless-stopped
    ports:
      - "5173:80"

  landing:
    build:
      context: ./landing
      args:
        PLATFORM_URL: http://self-study.xakker.org:5173
    container_name: xakker_landing
    restart: unless-stopped
    ports:
      - "5174:80"
