server {
    listen 80;
    server_name xakker.org www.xakker.org;

    location / {
        proxy_pass http://landing:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name self-study.xakker.org;

    location / {
        proxy_pass http://app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
